### PR TITLE
Make external directory configurable for each task

### LINKED ISSUE #58: Allow specification of external directory
Currently, praktomat executes the checker script in a separate docker container. If configured, it mounts an external directory into this container. Typically, this directory contains tests and solutions to all exercises for the semester.

I would like to make the directory to be mounted to be configurable for every task. Every praktomat instance would get a new configuration variable:

```
EXTERNAL_PATH = "/.../praktomat-tests/python-prog2/$TASK_ID/"
```

`$TASK_ID` is replaced with the ID of the task. This ID can be specified in a new field of the task. (String replacement works with python's template class). The ID of a task should be made available to the checker script via an environment variable `PRAKTOMAT_TASK_ID`.

More changes:

- Once praktomat supports these two features, we have to change the praktomat-tests repository so that the directory for a certain exercise no longer contains the solution. We can move to solution directory out and symlink it.
- We need to adjust the multi-checker in praktomat-checkers

### PR DESCRIPTION
**Pull request by hannesbraun**
In the `DOCKER_CONTAINER_EXTERNAL_DIR`, the string `${TASK_ID}` will be replaced with the specified custom id of a task. If it is not given, the string for the external directory will not be altered.

This id is also available as an environment variable within a checker as `TASK_ID_CUSTOM`. I chose this name to keep the naming consistent. (There is already an environment variable set for the checkers called `TASK_ID`.)

Closes #58

### CODE REVIEW

**Review by skogsbaer — CHANGES_REQUESTED** [review]
Very good! The only thing I do not like: the environment variable is called TASK_ID_CUSTOM, but in the external path, the variable is called ${TASK_ID}. Can you change the variable name in the external path to ${TASK_ID_CUSTOM}?

**Comment by hannesbraun** [comment]
> The only thing I do not like: the environment variable is called TASK_ID_CUSTOM, but in the external path, the variable is called ${TASK_ID}. Can you change the variable name in the external path to ${TASK_ID_CUSTOM}?

Sure, this should be fixed now.

**Review by skogsbaer — APPROVED** [review]

**Comment by skogsbaer** [comment]
One hint: do not force push after a review has been made. Reasons: you can now longer access certain review comments, because the commits no longer exists and the reviewer cannot see the diff between the version he reviewed and the new version.

**Comment by hannesbraun** [comment]
Okay, good to know. Although the diff should be visible through the "Compare" button in the "Conversations" tab of this pull request: 
Bildschirmfoto 2024-09-10 um 11 00 11

https://github.com/hso-praktomat/praktomat/compare/3520768a0da5f80eb9acb90d35aa10b47d54e5fc..4a81716b2d4750d67cc0c8dbc9753cd9d2a4ba7f

**Pull request merged**
